# @no-log
GET http://localhost:5000/sso?redirect_uri=https://example.com/verify/&user=johnston_k

###
# @no-log
GET http://localhost:5000/sso/verify/a5332d6b7a54baf4cd970ec3b33be443

###

# @no-log
GET http://localhost:5000/api/employeeLdap/johnston_k

###
